### ISSUE TITLE
Template file not found: notestutorial-main

### ISSUE THREAD

**Issue by artogahr** [nextcloud/app-tutorial#194]
I've been trying to learn to develop a Nextcloud app. I tried to go through with the steps but on my Nextcloud 19 instance following [this tutorial](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html) always results in a broken app right after the database migration. Then I tried to download the finished app from this repo, but when I import the app I get the following error:
![image](https://user-images.githubusercontent.com/22445057/91032475-a7f2f380-e60a-11ea-9abb-b0611783c3ec.png)
I suspect this is because the nextcloud app generator only supporting apps up to version 15 and old apps not working on version 19. Am I doing something wrong?

Nextcloud version: 19.0.1

**Comment by skjnldsv** [comment]
Right, that is a mistake! Fixed in https://github.com/nextcloud/app-tutorial/pull/195 :)

**Comment by artogahr** [comment]
Just tried, works now. Thanks!

**Comment by artogahr** [comment]
Any idea why the app breaks after the "increment version to migrate database" section of [the tutorial](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html)? I'm trying to do everything just as instructed there.

**Comment by skjnldsv** [comment]
> the app breaks

What does "break" means?

**Comment by artogahr** [comment]
In the migration step, an error would occur, Nextcloud would go into maintenance mode and when I get it out of maintenance the app would refuse to be enabled. But weirdly enough I tried it now and didn't get same issue. I'll create another issue if something weird happens again, thanks.

**Comment by skjnldsv** [comment]
I needs logs :)
