### ISSUE TITLE
How to get updated .js files (browser cache question)

### ISSUE THREAD

**Issue by githubkoma** [nextcloud/app-tutorial#25]
Hey There,

didnt know exactly where to put this question, but its related to this tutorial as i used this as a basis to start developing a nextcloud app..

After several changes and versions of the app, i often have the problem that webclients dont get the updated .js files..

lets say i have an additional js file: `<script src="/nextcloud/apps/notestutorial/js/notestutorial2.js"></script>`

Usually there is the way to add the following in the html header, e.g.:
`<script src="/nextcloud/apps/notestutorial/js/notestutorial2.js?v=2019090212345"></script>`

This "should" act as some kind of cachebuster to force the client to load the newest .js files from the server.. But that style is not supported with the nextcloud app framework.

Here is the way this is declared in Nextcloud App Framework main.php:
```
<?php
script('notestutorial', 'notestutorial');
script('notestutorial', 'notestutorial2');
?>
```

How can i achieve my goal to let the users get the updated js files (and html..) after the nextcloud app was updated via increasing the version number in info.xml?

I'm thankful for any hint :-)

**Comment by juliushaertl** [comment]
Hi,

Nextcloud will automatically append a cachebuster depending on your apps version to the script tag. When developing try disabling the browser cache in your browsers development tools or by force reloading.

For further general questions we also have a dedicated app developer section in our forum: https://help.nextcloud.com/c/dev/app-dev

Happy coding :wink:
