### ISSUE TITLE
Migration not working

### ISSUE THREAD

**Issue by lbm-services** [nextcloud/app-tutorial#259]
Depending on the exexcution method with full 'Version'-Classname or without, its either 

 php ./occ migrations:execute notestutorial Version000000Date20181013124731

In MigrationService.php line 396:
                                                       
  Version Version000000Date20181013124731 is unknown.  

In MigrationService.php line 458:
                                                                                           
  Migration step 'OCA\NotesTutorial\Migration\Version000000Date20181013124731' is unknown

**Comment by skjnldsv** [comment]
Can't reproduce :/
