### ISSUE TITLE
PHP Unittests Fail

### ISSUE THREAD

**Issue by Tom-Finke** [nextcloud/app-tutorial#274]
When I Clone the Repository and run the Unittests, i get the following error:

```
PHP Warning:  require_once(installdir/app-tutorial/tests/../../../tests/bootstrap.php): failed to open stream: No such file or directory in installdir/app-tutorial/tests/bootstrap.php on line 3
PHP Fatal error:  require_once(): Failed opening required 'installdir/app-tutorial/tests/../../../tests/bootstrap.php' (include_path='.:/usr/share/php') ininstalldir/app-tutorial/tests/bootstrap.php on line 3
```

Are there any prerequisites for running the Unittests?
What is going on with the Bosstrap.php? Why does it require itself but from 3 Directories up?
How Can I get the Unittests to run?

Im trying to develop a Nextcloud App and I can only run the unnitests via Github Actions, which makes debugging very tedious because I have to push every time.

**Comment by kesselb** [comment]
Hey :wave: 

`make dev-setup` to prepare the environment
`make test` to run the tests

> Why does it require itself but from 3 Directories up?

It loads the bootstrapping file from Nextcloud server. The usual environment to develop an Nextcloud app is a local installation of nextcloud/server and the app code in server/apps/$appId. 

> installdir/app-tutorial/tests/

https://github.com/nextcloud/app-tutorial/blob/a4fbfe46b001ede5edcd8b336e508faedd91f9dd/appinfo/info.xml#L4

The app if is notestutorial. It's a convention that the name of the folder matches the app id. So the app must be installed in installdir/notestutorial.
