### ISSUE TITLE
node-sass is deprecated

### ISSUE THREAD

**Issue by blizzz** [nextcloud/app-tutorial#281]
from https://www.npmjs.com/package/node-sass:

> Warning: LibSass and Node Sass are deprecated. While they will continue to receive maintenance releases indefinitely, there are no plans to add additional features or compatibility with any new CSS or Sass features. Projects that still use it should move onto [Dart Sass](https://sass-lang.com/dart-sass).

**Comment by blizzz** [comment]
@skjnldsv

**Comment by blizzz** [comment]
dart-sass is also recommended by sass-loader. looks like a drop-in replacement?

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/webpack-vue-config

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/webpack-vue-config/pull/82
