### ISSUE TITLE
'make test' fails out-of-the-box

### ISSUE THREAD

**Issue by robbieh** [nextcloud/app-tutorial#363]
After a fresh clone of the project and after running `make compose`, I can't get unit tests to work. Since this is my first go at building an app, I'm completely lost for what to do next.

```
./vendor/phpunit/phpunit/phpunit -c phpunit.xml
PHP Warning:  require_once(/var/www/nextcloud/apps/app-tutorial/tests/../../../tests/bootstrap.php): Failed to open stream: No such file or directory in /var/www/nextcloud/apps/app-tutorial/tests/bootstrap.php on line 3
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/nextcloud/apps/app-tutorial/tests/../../../tests/bootstrap.php' (include_path='.:/usr/share/php') in /var/www/nextcloud/apps/app-tutorial/tests/bootstrap.php:3
Stack trace:
#0 /var/www/nextcloud/apps/app-tutorial/vendor/phpunit/phpunit/src/Util/FileLoader.php(66): include_once()
#1 /var/www/nextcloud/apps/app-tutorial/vendor/phpunit/phpunit/src/Util/FileLoader.php(54): PHPUnit\Util\FileLoader::load()
#2 /var/www/nextcloud/apps/app-tutorial/vendor/phpunit/phpunit/src/TextUI/Command.php(1126): PHPUnit\Util\FileLoader::checkAndLoad()
#3 /var/www/nextcloud/apps/app-tutorial/vendor/phpunit/phpunit/src/TextUI/Command.php(922): PHPUnit\TextUI\Command->handleBootstrap()
#4 /var/www/nextcloud/apps/app-tutorial/vendor/phpunit/phpunit/src/TextUI/Command.php(202): PHPUnit\TextUI\Command->handleArguments()
#5 /var/www/nextcloud/apps/app-tutorial/vendor/phpunit/phpunit/src/TextUI/Command.php(194): PHPUnit\TextUI\Command->run()
#6 /var/www/nextcloud/apps/app-tutorial/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
#7 {main}
  thrown in /var/www/nextcloud/apps/app-tutorial/tests/bootstrap.php on line 3
make: *** [Makefile:70: test] Error 255

```

**Comment by brjhaverkamp** [comment]
H Robbiesh, you beat me to it with this issue. I ran into it as well yesterday.  
The workaround for you and me for the moment is to comment out the two lines in the test section at the end of app-tutorial/Makefile:
# Tests
test:
#	./vendor/phpunit/phpunit/phpunit -c phpunit.xml
#	./vendor/phpunit/phpunit/phpunit -c phpunit.integration.xml
At least it will finish building then.
I have no idea what bootstrap.php  the test is searching for. /var/www/nextcloud/apps/app-tutorial/tests/../../../tests/bootstrap.php doesn't exist and nothing in the neighborhood looks an obvious target. So I hope one of the devs can help here.

Bert

**Comment by robbieh** [comment]
I had been doing `make build-js-production` to get the same result, but that's a smart shortcut.

If I remove two levels of `..` from the bootstrap.php file, it looks like a workaround, but then a new error emerges:
```
PHP Fatal error:  Uncaught Error: Class "OCA\NotesTutorial\Tests\Unit\Controller\NoteControllerTest" not found in /var/www/nextcloud/apps/app-tutorial/tests/Unit/Controller/NoteApiControllerTest.php:7
```

**Comment by brjhaverkamp** [comment]
Hi Robieh

Not sure if I understand you correctly. If you remove two levels of .. from that line in tests/bootstrap it reads
`require_once __DIR__ . '/../tests/bootstrap.php';`
But that is pointing to itself, no? That doesn't seem to make sense as well.

Did you manage to build the app now? 
I am currently stuck at issue #6 https://github.com/nextcloud/app-tutorial/issues/6
"Could not download app notestutorial"
So any pointer on a workaround for that one is appreciated:-)

**Comment by robbieh** [comment]
@brjhaverkamp Check #6. I put in a note that might help.
And yes, I get that the change doesn't make much sense. I get the same effect from just commenting out the `require_once`.
