### ISSUE TITLE
build-js failed due to absence of dependancies like webpack, vue-loader, etc...

### ISSUE THREAD

**Issue by navid-dada** [nextcloud/app-tutorial#368]
I clone the repository to the NextCloud server that was configured by [this](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html) link. When I Run **make setup-dev** all thins are ok but when I run **make build-js** I am encountering with  this error: 

webpack --node-env development --progress

sh: 1: webpack: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! notestutorial@19.0.0 dev: `webpack --node-env development --progress`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the notestutorial@19.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/navid/.npm/_logs/2022-01-17T19_17_30_482Z-debug.log
make: *** [Makefile:36: build-js] Error 1

when I install Webpack manually many other packages raise the absence error. Is there any straightforward solution to solve this issue?

**Comment by skjnldsv** [comment]
Please use npm 7
https://github.com/nextcloud/app-tutorial/blob/50d5d21bcd9572d6db19a37b62032750ee95817b/package.json#L40-L41

**Comment by skjnldsv** [comment]
Actually, there was also another bug with `@nextcloud/webpack-vue-config`
Fixed in https://github.com/nextcloud/app-tutorial/pull/372
