### ISSUE TITLE
Wrong Link in README.md

### ISSUE THREAD

**Issue by mrtzkdev** [nextcloud/app-tutorial#97]
The link to the according docs Page doesn't work.

`https://docs.nextcloud.com/server/latest/developer_manual/app/tutorial.html`
has to be changed into:
`https://docs.nextcloud.com/server/13.0.0/developer_manual/app/tutorial.html`

**Comment by juliushaertl** [comment]
Our sysadmin team is informed and will try to get the latest documentation up again soon. We are currently at Nextcloud 18 so we should not link old docs like the 13 ones.
